//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kozin41
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int OrderID { get; set; }
        public string ProductArticleNumber { get; set; }
        public int ProductQuantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }

        public decimal ItemTotal
        {
            get
            {
                if (Product == null) return 0;
                decimal price = Product.ProductCost;
                decimal discount = price * (Product.ProductDiscountAmount / 100m);
                return (price - discount) * ProductQuantity;
            }
        }
    }
}
